configuration: 
  name: hellobioqa
  author: team01
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: hellobioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  file: /input/trecgen06.txt

pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
     - inherit: hellobioqa.team01.keyterm.simple
      
  #- inherit: jdbc.sqlite.cse.phase  
  #  name: mesh-keyterm-updater
  #  options: |
   #  - inherit: hellobioqa.team01.keyterm.mesh
     
  - inherit: jdbc.sqlite.cse.phase  
    name: deduplicate-keyterm-updater
    options: |
     - inherit: hellobioqa.team01.keyterm.deduplicate
  
  - inherit: jdbc.sqlite.cse.phase  
    name: deduplicate-keyterm-updater
    options: |
     - inherit: hellobioqa.team01.keyterm.filterstop
     
 # - inherit: jdbc.sqlite.cse.phase 
  #  name: retrieval-strategist
   # options: |
    #  - inherit: hellobioqa.retrieval.query-expanding-strategist

     
  #- inherit: jdbc.sqlite.cse.phase 
  #  name: retrieval-strategist
  #  options: |
   #   - inherit: hellobioqa.retrieval.boostedsimple-solr-strategist
      
    inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: hellobioqa.retrieval.combine
      
         
         
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      #- inherit: hellobioqa.passage.simplecorrected
      - inherit: hellobioqa.passage.sentencebased-passage-extractor
      
  - inherit: helloqa.eval.keyterm-aggregator-consumer

  - inherit: jdbc.eval.retrieval-aggregator-consumer
      
  - inherit: helloqa.eval.passage-map-aggregator-consumer      
    
post-process: 
  - inherit: helloqa.eval.keyterm-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.keyterm-report-component
  
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
          
  - inherit: helloqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.map-report-component
  
