configuration: 
  name: hellobioqa
  author: team01
  
persistence-provider:
  inherit: helloqa.db.local-persistence-provider

collection-reader:
  inherit: hellobioqa.collection.decorated-collection-reader
  dataset: TRECGEN06
  file: /input/small-trecgen06.txt

pipeline:
  - inherit: jdbc.sqlite.cse.phase
    name: keyterm-extractor
    options: |
      - inherit: helloqa.keyterm.simple
     
  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: hellobioqa.retrieval.simple-solr-strategist
          
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      - inherit: hellobioqa.passage.simple-corrected
      
  - inherit: helloqa.eval.keyterm-aggregator-consumer

  - inherit: jdbc.eval.retrieval-aggregator-consumer
      
  - inherit: helloqa.eval.passage-map-aggregator-consumer      
    
post-process: 
  - inherit: helloqa.eval.keyterm-evaluator-consumer
  - inherit: hellobioqa.report.hbqa-report-generator
    builders: |
        - inherit: helloqa.report.keyterm-report-component
       #- inherit: hellobioqa.report.hbqa-report-generator
  
  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
          
  - inherit: helloqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: helloqa.report.map-report-component
  